### PR TITLE
Draw timers window when at least one timer is activated

### PR DESCRIPTION
**Pull request by xPumaa**

### CODE REVIEW

**Comment by MidoriKami** [comment]
I don't understand the use case for this feature.

**Comment by xPumaa** [comment]
I think it's more a preference for the kind of programming.
I don't necessarily want to show the user an empty window.

**Comment by MidoriKami** [comment]
image

**Comment by xPumaa** [comment]
Okay, this is even the better option

**Comment by MidoriKami** [comment]
Took longer to implement the word-wrap feature than anything else haha

**Pull request closed without merging**
