### PR TITLE
Added Plus80 notification mode for fashion report

### PR DESCRIPTION
**Pull request by xPumaa**

### CODE REVIEW

**Review by MidoriKami — APPROVED** [review]
I dig it. Thanks.

**Comment by MidoriKami** [comment]
How bad was it to navigate and modify DailyDuty?

**Comment by xPumaa** [comment]
So far it has been super easy. The code is clear, understandable and well structured.
There are a few things that could be simplified a bit, like the FashionReportAvailable() function call, but nothing major or that affects performance.

**Comment by MidoriKami** [comment]
I took a look at FashionReportAvailable and came up with this: https://github.com/MidoriKami/DailyDuty/commit/04e4af871db6580738db0124abbd676ca97d7848

Let me know what you think.

**Comment by xPumaa** [comment]
That's pretty cool. I didn't know you could use "when" in the case statement. Learned something new again today.

**Comment by MidoriKami** [comment]
I found that syntax because of your comment to simplify it haha

I use that syntax to great effect in the new AddonModule System too

```cs
            if (Settings.Enabled && IsWeeklyInputWindowOpen())
            {
                switch (eventType)
                {
                    case AtkEventType.MouseDown when a5->RightClick == false && atkUnitBase == GetPurchaseButton():

                        var button = (AtkComponentButton*) atkUnitBase;

                        if (button->IsEnabled)
                        {
                            purchaseButtonPressed = true;

                            AddonManager.YesNoAddonHelper.ResetState();
                        }
                        break;

                    default:
                        break;
                }
            }
```

**Pull request merged**
